// // Switch to the video-stream database
// use video-stream
//
// // Create a collection for users
// db.createCollection("users")
//
// // Insert some users
// db.users.insertMany([
//     {
//         "user_id": 1,
//         "first_name": "Ibrahim",
//         "last_name": "Imam",
//         "age": 31,
//         "role": "ADMIN",
//         "username": "ibu",
//         "password": "hashed_password_here",
//         "contact": {
//             "phone": "+15205994323",
//             "email": "ibrahim.imam642@gmail.com"
//         },
//         "address": {
//             "street": "s",
//             "city": "city",
//             "state": "ca",
//             "zipcode": "12334"
//         }
//     },
//     {
//         "user_id": 2,
//         "first_name": "Abi",
//         "last_name": "Zaki",
//         "age": 45,
//         "role": "ADMIN",
//         "username": "abule",
//         "password": "hashed_password_here",
//         "contact": {
//             "phone": "+15205778890",
//             "email": "imam642@gmail.com"
//         },
//         "address": {
//             "street": "400w Washington",
//             "city": "Fairfield",
//             "state": "IA",
//             "zipcode": "52556"
//         }
//     }
// ])
